### ISSUE TITLE
formatting issue in output of `show-comparison-groups`

### ISSUE THREAD

**Issue by gregcaporaso** [colinvwood/q2-qsip2#2]
Following the tutorial steps with the provided data, it looks like the output of `show-comparison-groups` is getting formatted strangely - noticed that the table appears to be cut off on the left side. 

![Screenshot 2024-09-18 at 4 32 57 PM](https://github.com/user-attachments/assets/4eee8f0b-5259-4ca5-a7c0-ef1688770813)

**Comment by colinvwood** [comment]
Strange, didn't happen to me in safari. This is just pandas' `df.to_html` method. I can add some left padding or something.

**Comment by colinvwood** [comment]
Seems like it's probably a q2-view problem because the html is dead simple with almost no CSS.

**Comment by gregcaporaso** [comment]
Weird. I'll send you the .qzv, and if it's working ok for you we can close this.

**Comment by gregcaporaso** [comment]
Seems to work fine for me in Chrome - I'm only having the issue in Firefox. So I agree, this probably isn't a q2-qsip2 issue.
